[package]
name = "rwlock"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.60"
ticket_fields = { path = "../../../helpers/ticket_fields" }

[lints.rust]
dead_code = "allow"
unused = "allow"
private_interfaces = "allow"
