[package]
name = "bounded"
version = "0.1.0"
edition = "2021"

[dependencies]
ticket_fields = { path = "../../../helpers/ticket_fields" }
thiserror = "1"

[lints.rust]
dead_code = "allow"
unused = "allow"
private_interfaces = "allow"
